# Kích hoạt pipeline khi có code mới đẩy lên nhánh master hoặc main
trigger:
- master
- main

# Sử dụng máy ảo Ubuntu mới nhất của Microsoft
pool:
  vmImage: ubuntu-latest

steps:
# Bước 1: Cài đặt Node.js version 16.x
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Bước 2: Chạy lệnh cài thư viện và build
- script: |
    npm install
    npm run build
  displayName: 'Run npm install and build'